import https from 'https';
import fs from 'fs';
import path from 'path';

// HTTPS configuration for offline/intranet deployment
export function createHttpsServer(app) {
  try {
    // Load SSL certificates generated by mkcert
    const options = {
      key: fs.readFileSync(path.join(process.cwd(), 'localhost+2-key.pem')),
      cert: fs.readFileSync(path.join(process.cwd(), 'localhost+2.pem'))
    };
    
    console.log('✅ SSL certificates loaded successfully');
    return https.createServer(options, app);
  } catch (error) {
    console.error('❌ Failed to load SSL certificates:', error.message);
    console.log('📋 Make sure localhost+2.pem and localhost+2-key.pem files exist in the project root');
    console.log('💡 Run: mkcert localhost 192.168.100.165 127.0.0.1');
    process.exit(1);
  }
}